// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnUytT44Jacvk9QM1Up3oKcehnji99pi4',
    appId: '1:362326812309:web:c557c9f2c4884967d95d9c',
    messagingSenderId: '362326812309',
    projectId: 'bazario-f81e3',
    authDomain: 'bazario-f81e3.firebaseapp.com',
    storageBucket: 'bazario-f81e3.firebasestorage.app',
    measurementId: 'G-6LRHS3LM0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1hvyN4GSnUrh3jXux8ijn7aFEhy3EL2U',
    appId: '1:362326812309:android:bb4f72e970529414d95d9c',
    messagingSenderId: '362326812309',
    projectId: 'bazario-f81e3',
    storageBucket: 'bazario-f81e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5wGdTZWnXLxViExJ5M5ub7W1znum8Rbk',
    appId: '1:362326812309:ios:f396dea5f0307845d95d9c',
    messagingSenderId: '362326812309',
    projectId: 'bazario-f81e3',
    storageBucket: 'bazario-f81e3.firebasestorage.app',
    iosBundleId: 'com.example.bazario',
  );
}
